#!/bin/bash

# Parameters
VENV=/home/rtd
APPDIR=$VENV/site/readthedocs.org/readthedocs # Django project directory
DJANGO_SETTINGS_MODULE=settings.local_srv # which settings file should Django use

# Activate the virtual environment
source $VENV/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$APPDIR:$PYTHONPATH

# Start Celery
exec $VENV/bin/python $VENV/site/readthedocs.org/manage.py celery worker
--settings=$DJANGO_SETTINGS_MODULE \
--loglevel=info
