#!/bin/bash

# Parameters
VENV=/home/rtd
APPDIR=$VENV/site/readthedocs.org/readthedocs
DJANGO_SETTINGS_MODULE=settings.local_srv
CONCURRENCY=1

# Activate the virtual environment
source $VENV/bin/activate

export P4CONFIG=$VENV/.p4config
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$APPDIR:$PYTHONPATH

# Start Celery
exec $VENV/bin/django-admin.py celeryd \
--settings=$DJANGO_SETTINGS_MODULE \
--loglevel=error \
--concurrency=$CONCURRENCY \
--events \
--beat
