#!/bin/bash

# Parameters
NAME="ReadTheDocs"
VENV=/home/rtd
APPDIR=$VENV/site/readthedocs.org/readthedocs
#SOCKFILE=$VENV/run/gunicorn.sock
USER=rtd
NUM_WORKERS=2
DJANGO_SETTINGS_MODULE=settings.local_srv

# Activate the virtual environment
source $VENV/bin/activate

export HOME=$VENV
export P4CONFIG=$VENV/.p4config
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$APPDIR:$PYTHONPATH

# Start Gunicorn
exec $VENV/bin/gunicorn_django \
--name=$NAME \
--user=$USER \
--workers=$NUM_WORKERS \
--preload \
--log-level=error \
--pid=$VENV/run/gunicorn.pid \
--bind=127.0.0.1:8888
